### PR TITLE
Tei magyarnarancs

### PR DESCRIPTION
**Pull request by zsofiar**
**Motivation**

Uploading configs for the preparation of the TEI XML related to the portal: `magyarnarancs`.

**Changes**

There are new config files available:
- `magyarnarancs_specifiy.py`
- `magyarnarancs_BASE.xml`
- `magyarnarancs_text_tags_normal.tsv`
- `magyarnarancs_notext_tags_normal.tsv`

**Notes**

The `magyarnarancs_BASE.xml` is not completed perfectly. I was not given the possibility to run the code on the whole warc file. Please keep in mind that modifications on the `magyarnarancs_BASE.xml` are still expected to be done. We will discuss that question on mattermost, at the Webaratás (TáTK) channel.

There are some questions coming up related to the authors (person or organisation). We will address those separately on mattermost and discuss whether we would like to collect those metadata in a more detailed manner. Details will arrive later on mattermost, at the Webaratás (TáTK) channel.

### CODE REVIEW

**Comment by zsofiar** [comment]
I have modified the warning related to the keywords according to @sarkozizsofia 's feedback. 
And an other modification has been introduces to handle author (natural person) and source (institutions etc.) differently. `AUTH_SOURCE` has been defined in the `magyarnarancs_specific.py` to gather organisations and entities that are not natural persons. This list is not necessarily exhaustive. That has been used as a parameter of the `get_meta_from_articles_spec` function.

**Comment by zsofiar** [comment]
**Updates**

- **Minor modification regarding the logging**
As it was suggested by @sarkozizsofia I have modified the level of the log used by the `tei_logger` (from `WARNING` to `DEBUG`) in order to mute the logging for `TAGS NOT FOUND!`. The portal does not always store keywords for the articles and there were numerous logs for the missing keywords in the `tei_writing_magyarnarancs.log` because of that, which made it harder to read the logs effectively. Thanks @sarkozizsofia for the advice!

- **Update on the `AUTH_SOURCE` variable**
I have searched for some organisations and for seemingly not natural persons, who typically publish articles at magyarnarancs.hu and have updated the `AUTH_SOURCE` accordingly. There are some elements that could be defined - in the future - as `source` instead of an `author`, these potential elements are commented in the code to provide a possibility to decide later whether to use them or not.

- **Further fine-tuning have been made to find and save the `date`s correctly**. 
The portal does NOT store the `date`s consequently. It uses different HTML structure for storing the `date`s of the different types of articles (originally offline articles, and online articles. So 1) the articles coming originally from the offline version of MagyarNarancs, and 2) the the online articles have different HTML structures to store the `date` metadata. The code applies rules to handle the problem flexibly. 

**Notes**
There aren't any further updates planned on this PR. Please @sarkozizsofia and @dlazesz let me know if you have any feedback and if necessary, I will rework the code accordingly. Thanks in advance for your feedback!

**Comment by zsofiar** [comment]
**Update on the `AUTH_SOURCE` variable**
Accordign to the questions coming back related to the `AUTH_SOURCE` variable, I have cleaned the list and removed the unnecessary comments.

**Comment by sarkozizsofia** [comment]
I left comments on Kanboard .

**Comment by zsofiar** [comment]
Thanks @sarkozizsofia for the comments on Kanboard. I have modified the code accordingly.

**Pull request merged**
